<mxfile host="Electron" agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/24.7.17 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36" version="24.7.17">
  <diagram name="Page-1" id="Dx_iZKQlpL04gCbXKIEB">
    <mxGraphModel dx="1205" dy="850" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1169" pageHeight="827" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="ZEnTwO2tOqJG3honPpXl-56" value="$(AM_HOME)/Makefile" style="swimlane;whiteSpace=wrap;html=1;" parent="1" vertex="1">
          <mxGeometry x="238" y="170" width="200" height="180" as="geometry">
            <mxRectangle x="520" y="300" width="140" height="30" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-58" value="初始化/检查参数" style="whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-56" vertex="1">
          <mxGeometry x="10" y="30" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-59" value="扫描目录,初始化编译链接对象" style="rounded=0;whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-56" vertex="1">
          <mxGeometry x="10" y="54" width="180" height="26" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-60" value="生成编译参数" style="rounded=0;whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-56" vertex="1">
          <mxGeometry x="10" y="84" width="180" height="26" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-61" value="include指定架构makefile" style="rounded=0;whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-56" vertex="1">
          <mxGeometry x="10" y="114" width="180" height="26" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-63" value="编译链接规则" style="rounded=0;whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-56" vertex="1">
          <mxGeometry x="10" y="144" width="180" height="26" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-64" value="$(AM_Programs)/Makefile" style="swimlane;whiteSpace=wrap;html=1;" parent="1" vertex="1">
          <mxGeometry x="18" y="260" width="200" height="90" as="geometry">
            <mxRectangle x="520" y="300" width="140" height="30" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-65" value="添加SRCS" style="whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-64" vertex="1">
          <mxGeometry x="10" y="30" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-66" value="include $(AM_HOME)/Makefile" style="rounded=0;whiteSpace=wrap;html=1;" parent="ZEnTwO2tOqJG3honPpXl-64" vertex="1">
          <mxGeometry x="10" y="54" width="180" height="26" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-76" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0.001;entryY=0.087;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="ZEnTwO2tOqJG3honPpXl-66" target="ZEnTwO2tOqJG3honPpXl-56" edge="1">
          <mxGeometry relative="1" as="geometry">
            <Array as="points">
              <mxPoint x="208" y="330" />
              <mxPoint x="228" y="330" />
              <mxPoint x="228" y="186" />
            </Array>
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-78" value="$(AM_HOME)/scripts/riscv32e-nemu" style="swimlane;whiteSpace=wrap;html=1;startSize=30;" parent="1" vertex="1">
          <mxGeometry x="458" y="150" width="200" height="100" as="geometry">
            <mxRectangle x="520" y="300" width="140" height="30" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-79" value="include $(AM_HOME)/scripts/isa/riscv.mk" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-78" vertex="1">
          <mxGeometry x="10" y="40" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-91" value="include $(AM_HOME)/platform/nemu.mk" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-78" vertex="1">
          <mxGeometry x="10" y="64" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-84" value="$(AM_HOME)/scripts/riscv32e-npc" style="swimlane;whiteSpace=wrap;html=1;startSize=30;" parent="1" vertex="1" collapsed="1">
          <mxGeometry x="458" y="280" width="200" height="30" as="geometry">
            <mxRectangle x="460" y="420" width="200" height="100" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-87" value="$(AM_HOME)/scripts/riscv32e-soc" style="swimlane;whiteSpace=wrap;html=1;startSize=30;" parent="1" vertex="1" collapsed="1">
          <mxGeometry x="458" y="320" width="200" height="30" as="geometry">
            <mxRectangle x="460" y="420" width="200" height="100" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-88" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.25;exitDx=0;exitDy=0;entryX=0.002;entryY=0.099;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="ZEnTwO2tOqJG3honPpXl-61" target="ZEnTwO2tOqJG3honPpXl-78" edge="1">
          <mxGeometry relative="1" as="geometry">
            <Array as="points">
              <mxPoint x="448" y="290" />
              <mxPoint x="448" y="160" />
            </Array>
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-89" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0.002;entryY=0.531;entryDx=0;entryDy=0;entryPerimeter=0;dashed=1;dashPattern=1 2;" parent="1" target="ZEnTwO2tOqJG3honPpXl-84" edge="1">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="428" y="296" as="sourcePoint" />
            <mxPoint x="458" y="293.99999999999994" as="targetPoint" />
            <Array as="points">
              <mxPoint x="458" y="296" />
            </Array>
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-90" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.75;exitDx=0;exitDy=0;entryX=0.003;entryY=0.35;entryDx=0;entryDy=0;entryPerimeter=0;dashed=1;dashPattern=1 2;" parent="1" source="ZEnTwO2tOqJG3honPpXl-61" target="ZEnTwO2tOqJG3honPpXl-87" edge="1">
          <mxGeometry relative="1" as="geometry">
            <Array as="points">
              <mxPoint x="448" y="304" />
              <mxPoint x="448" y="330" />
            </Array>
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-93" value="&lt;font style=&quot;font-size: 12px;&quot;&gt;$(AM_HOME)/scripts/isa/riscv.mk&lt;/font&gt;" style="swimlane;whiteSpace=wrap;html=1;startSize=20;" parent="1" vertex="1">
          <mxGeometry x="690" y="150" width="200" height="60" as="geometry">
            <mxRectangle x="520" y="300" width="140" height="30" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-94" value="&lt;span style=&quot;font-size: 12px;&quot;&gt;交叉编译器和各种编译参数&lt;/span&gt;" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-93" vertex="1">
          <mxGeometry x="10" y="30" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-96" value="&lt;font style=&quot;font-size: 12px;&quot;&gt;$(AM_HOME)/platform/nemu.mk&lt;/font&gt;" style="swimlane;whiteSpace=wrap;html=1;startSize=20;" parent="1" vertex="1">
          <mxGeometry x="690" y="220" width="200" height="80" as="geometry">
            <mxRectangle x="520" y="300" width="140" height="30" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-97" value="&lt;span style=&quot;font-size: 12px;&quot;&gt;AM源文件,链接脚本,image,run,gdb的各种target&lt;/span&gt;" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-96" vertex="1">
          <mxGeometry x="10" y="30" width="180" height="40" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-102" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.25;exitDx=0;exitDy=0;entryX=0;entryY=0.25;entryDx=0;entryDy=0;" parent="1" source="ZEnTwO2tOqJG3honPpXl-79" target="ZEnTwO2tOqJG3honPpXl-93" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-104" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.75;exitDx=0;exitDy=0;entryX=0.001;entryY=0.176;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="ZEnTwO2tOqJG3honPpXl-91" target="ZEnTwO2tOqJG3honPpXl-96" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-105" value="&lt;font style=&quot;font-size: 12px;&quot;&gt;$(NEMU_HOME)/Makefile&lt;/font&gt;" style="swimlane;whiteSpace=wrap;html=1;startSize=20;" parent="1" vertex="1">
          <mxGeometry x="690" y="340" width="200" height="130" as="geometry">
            <mxRectangle x="520" y="300" width="140" height="30" as="alternateBounds" />
          </mxGeometry>
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-106" value="&lt;span style=&quot;font-size: 12px;&quot;&gt;&lt;b&gt;NEMU&lt;/b&gt; compile rules&lt;/span&gt;" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-105" vertex="1">
          <mxGeometry x="10" y="25" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-121" value="&lt;font style=&quot;font-size: 11px;&quot;&gt;include $(NEMU_HOME)/build.mk&lt;/font&gt;" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-105" vertex="1">
          <mxGeometry x="10" y="50" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-124" value="&lt;font style=&quot;font-size: 11px;&quot;&gt;include $(NEMU_HOME)/config.mk&lt;/font&gt;" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-105" vertex="1">
          <mxGeometry x="10" y="76" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="ZEnTwO2tOqJG3honPpXl-125" value="&lt;font style=&quot;font-size: 11px;&quot;&gt;include $(NEMU_HOME)/native.mk&lt;/font&gt;" style="whiteSpace=wrap;html=1;fontSize=9;" parent="ZEnTwO2tOqJG3honPpXl-105" vertex="1">
          <mxGeometry x="10" y="102" width="180" height="20" as="geometry" />
        </mxCell>
        <mxCell id="lFsHeVHzT1lcJdY5Tgx7-1" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=0.5;exitY=1;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;sketch=1;curveFitting=1;jiggle=10;enumerate=0;orthogonal=0;sketchStyle=comic;strokeWidth=2;strokeColor=#B5739D;" parent="1" source="ZEnTwO2tOqJG3honPpXl-97" target="ZEnTwO2tOqJG3honPpXl-105" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="lFsHeVHzT1lcJdY5Tgx7-2" value="Text" style="text;html=1;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;" parent="1" vertex="1">
          <mxGeometry x="690" y="360" width="60" height="30" as="geometry" />
        </mxCell>
        <mxCell id="lFsHeVHzT1lcJdY5Tgx7-4" value="&lt;b&gt;MAKE&lt;/b&gt;" style="text;html=1;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;" parent="1" vertex="1">
          <mxGeometry x="780" y="310" width="50" height="20" as="geometry" />
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
